{{- if and .Values.ingress.enabled (not .Values.faas.enabled) }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "k8s-app.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k8s-app.labels" . | nindent 4 }}
  annotations:
    {{- include "k8s-app.annotations" . | nindent 4 }}
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: apps-lb
    platform.k8s.ukatru.com/dns-name: {{ include "k8s-app.dnsName" . }}
    {{- if eq .Values.appSpec.language "spa" }}
    alb.ingress.kubernetes.io/healthcheck-port: "{{ .Values.service.port | default 8080 }}"
    {{- else }}
    alb.ingress.kubernetes.io/healthcheck-path: {{ .Values.lifecycle.livenessProbe.path | default "/health" }}
    {{- end }}
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/security-groups: {{ .Values.clusterConfig.securityGroupId }}
    alb.ingress.kubernetes.io/subnets: {{ .Values.clusterConfig.albSubnet }}
    alb.ingress.kubernetes.io/certificate-arn: {{ .Values.clusterConfig.certArn }}
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className | default "alb" }}
  rules:
  - host: {{ include "k8s-app.dnsName" . | quote }}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: {{ include "k8s-app.fullname" . }}
            port:
              number: {{ include "k8s-app.appPort" . }}
{{- end }}
